export const meetExpandedCopy = {
  service: [
    `His approach to public service is centered around three words that describe both what residents should expect from their emergency services district and the standards he believes should guide effective public governance:`,
    `Prepared. Responsive. Transparent.`,
    `Harris County Emergency Services District No. 9 is the local governmental entity responsible for providing fire protection, emergency medical services, emergency response, and related public-safety services throughout the Cy-Fair community. These services are delivered by the nearly 580 men and women who work and volunteer as members of the Cy-Fair Fire Department.`,
    `Serving a large and growing population of approximately 650,000 residents across approximately 165 square miles, HCESD9 is responsible for the resources, facilities, personnel, apparatus, equipment, and long-term planning necessary to provide high-quality and reliable fire, emergency medical, and other emergency-response services to the community.`,
    `The five-member Board of Commissioners provides governance and public oversight of the District. Commissioners are responsible for adopting the annual budget and tax rate, overseeing the responsible stewardship of taxpayer resources, establishing policies and strategic priorities, planning for future fire stations and other capital needs, and providing oversight and evaluation of the Fire Chief and the District's overall organizational and operational performance.`,
    `As Commissioner and Vice President, Mr. Dickey brings his experience in executive leadership, financial management, strategic planning, governance, and community service to the Board, with a particular emphasis on strong financial stewardship, long-term preparedness, measurable organizational performance, transparency, and accountability to the taxpayers the District serves.`,
  ],
  family: [
    `Cameron's oldest daughter, McKenna, has been accompanying her dad to community and business events since she was three years old—when she could be found sitting in the front row of the annual meeting of Multco Credit Union, where Cameron was then Chief Financial Officer. Smart, animated, and a gifted storyteller, McKenna eventually followed her father's footsteps into financial services. After attending college, she has built a successful career of her own in insurance and mortgage lending and, today, lives and works in Cypress.`,
    `His second daughter, Cassidy, ventured farther from home after high school, attending the University of Arizona and earning a degree in Business Administration. Since graduation, she has built an impressive career through positions of increasing management responsibility with a nationwide specialty beauty retailer. Cassidy and her husband live just North of Houston in Willis, Texas.`,
    `Cameron's youngest daughter, Ella, is a college sophomore, a talented artist, and perhaps an illustration of just how varied the interests within the Dickey family can be. She is currently pursuing a double major in Cybersecurity and Computer Science, combining her creative talents with an interest in technology.`,
    `And the "baby" of the family, Dillon, is now a high school senior and dedicated athlete. After graduation, he currently plans to attend Arizona State University—his father's alma mater—where he intends to study Business Administration.`,
  ],
  loss: [],
  roots: [
    `Together, Lois and Rex built and operated six different businesses. But the legacy Cameron values most isn't found on a résumé. It is the example his parents provided through 55 years of marriage—a remarkable story of love, perseverance, faith, hard work, and commitment to one another and their family.`,
    `Those same lessons have shaped Cameron's own life: that family comes first; that commitments matter; that difficult seasons are faced rather than avoided; and that whatever talents, experiences, and opportunities we are given carry with them a responsibility to use them in service to others.`,
    `Today, Cypress is where Cameron raised his children, where members of his family continue to live and work, and where he has spent more than a decade building relationships and serving his neighbors. It isn't simply where he lives. It's the community his family calls home.`,
  ],
  faith: [
    `As he grew older, those beliefs increasingly found expression through service. He participated extensively in Vacation Bible School, led a men’s small-group Bible study, and helping with weekly offertory service.`,
    `Beginning in 2003, Cameron also participated in Christian mission work in Kenya. His service there included helping with a church expansion project, participating in worship services, and working with children at an orphanage in Nairobi and, on a later trip, in Busia, Kenya.`,
    `Those experiences left a lasting impression on him—particularly seeing the faith, compassion, and commitment of other families in their church who adopted children growing up in foster care or orphans from developing countries around the world.`,
    `Ultimately, those examples planted a seed for Cameron and Kimberly, who years later expanded their own family through adoption. For Cameron, that journey was closely connected to his faith and a concern for children that had been developing since that first mission experience.`,
    `Cameron and Kimberly raised their children in the church, and prayer remains central to their household. That foundation became particularly meaningful during Kimberly’s nearly six-year battle with breast cancer and following her death in 2019, just months before what would have been their 25th wedding anniversary. Cameron’s faith did not remove the grief of losing his wife, but it provided strength, hope, and a foundation for continuing to raise their children and move forward together as a family.`,
    `Today, Cameron is a member of Foundry Church. His pastor, Ray Hughes, is also a longtime friend who has watched Cameron’s children grow up and walked alongside the Dickey family through some of its most important and difficult moments.`,
    `For Cameron, this life-long foundation has shaped his understanding of marriage and fatherhood, influenced his family’s decisions, called him to serve people far from home, sustained him through profound loss, and reinforced a belief that our lives have greater meaning when we use what we have been given in service to others.`,
    `Cameron recognizes that faith is not a requirement for public service. The work of the District belongs equally to every resident it serves, regardless of faith, background, or belief.`,
    `But public service is ultimately carried out by people, and Cameron believes the values, and character a person brings to that responsibility matter. His faith has helped shape his own—teaching him about humility, compassion, integrity, empathy, accountability, perseverance, and the responsibility to serve others.`,
    `Those principles influence the kind of husband and father Cameron has sought to be, the way he has approached more than three decades of professional and community leadership, and the standard he sets for himself when entrusted with responsibilities that affect others.`,
  ],
} as const
